-- PlayerSetilderCantBeCaptured
-- Author: SS
-- DateCreated: 4/18/2024 2:52:02 PM
--------------------------------------------------------------
INSERT INTO Types
(	Type,												Kind) VALUES
(	'ABILITY_BUILDER_DECREASE_BUILD_CHARGES',			'KIND_ABILITY'),
(	'ABILITY_BUILDER_INCREASE_BUILD_CHARGES',			'KIND_ABILITY'),
(	'MODIFIER_UNIT_BUILDER_ADJUST_BUILDER_CHARGES',		'KIND_MODIFIER');

INSERT INTO DynamicModifiers
(	ModifierType,										CollectionType,			EffectType) VALUES
(	'MODIFIER_UNIT_BUILDER_ADJUST_BUILDER_CHARGES',		'COLLECTION_OWNER',		'EFFECT_ADJUST_UNIT_BUILD_CHARGES');

INSERT INTO TypeTags
(	Type,										Tag) VALUES
(	'ABILITY_BUILDER_DECREASE_BUILD_CHARGES',	'CLASS_BUILDER'),
(	'ABILITY_BUILDER_INCREASE_BUILD_CHARGES',	'CLASS_BUILDER');

INSERT INTO UnitAbilities
(	UnitAbilityType,							Name,													Description,												Inactive) VALUES
(	'ABILITY_BUILDER_DECREASE_BUILD_CHARGES',	'LOC_ABILITY_BUILDER_DECREASE_BUILD_CHARGES_NAME',		'LOC_ABILITY_BUILDER_DECREASE_BUILD_CHARGES_DESCRIPTION',	1),
(	'ABILITY_BUILDER_INCREASE_BUILD_CHARGES',	'LOC_ABILITY_BUILDER_INCREASE_BUILD_CHARGES_NAME',		'LOC_ABILITY_BUILDER_INCREASE_BUILD_CHARGES_DESCRIPTION',	1);


INSERT INTO UnitAbilityModifiers
(	UnitAbilityType,							ModifierId) VALUES
(	'ABILITY_BUILDER_DECREASE_BUILD_CHARGES',	'MODIFIER_ABILITY_BUILDER_DECREASE_BUILD_CHARGES'),
(	'ABILITY_BUILDER_INCREASE_BUILD_CHARGES',	'MODIFIER_ABILITY_BUILDER_INCREASE_BUILD_CHARGES');


INSERT INTO Modifiers
(	ModifierId,												ModifierType,										RunOnce,	Permanent,		NewOnly,	OwnerRequirementSetId,		SubjectRequirementSetId) VALUES
(	'MODIFIER_ABILITY_BUILDER_DECREASE_BUILD_CHARGES',		'MODIFIER_UNIT_BUILDER_ADJUST_BUILDER_CHARGES',		0,			1,				0,			NULL,						NULL),
(	'MODIFIER_ABILITY_BUILDER_INCREASE_BUILD_CHARGES',		'MODIFIER_UNIT_BUILDER_ADJUST_BUILDER_CHARGES',		0,			1,				0,			NULL,						NULL);


INSERT INTO ModifierArguments
(	ModifierId,												Name,		Value) VALUES
(	'MODIFIER_ABILITY_BUILDER_DECREASE_BUILD_CHARGES',		'Amount',	'-1'),
(	'MODIFIER_ABILITY_BUILDER_INCREASE_BUILD_CHARGES',		'Amount',	'1');

